version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.3
      - image: circleci/mariadb:10.2
    steps:
      - checkout

      # We are using a single Machine User user key for checking out, pulling and pushing to multiple repos
      # So we don't need an additional add_ssh_keys step to facilitate additional SSH deploy keys
      - run:
          name: testing Circle Ci PR merged
          command: |
            echo "R $CIRCLE_PULL_REQUEST"
            echo "Rs $CIRCLE_PULL_REQUESTS"
            echo "SHA $CIRCLE_SHA1"

workflows:
  version: 2
  build-workflow:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
